Repository privacy-scaling-explorations/zk-kit, pull requests merged in 2022-02, with the labels that each got.

#14 Fix/nrln removal
  packages/identity/src/identity.ts
  packages/identity/src/index.ts
  packages/identity/tests/index.test.ts
  packages/protocols/src/index.ts
  packages/protocols/src/nrln.ts
  packages/protocols/tests/nrln.test.ts
  packages/protocols/tests/rln.test.ts
  types/zk-kit/index.d.ts
Labels: enhancement

#17 fix(incremental-merkle-tree): merkle tree supports zero leaves. Merkle proof fails for zero value
  packages/incremental-merkle-tree/package.json
  packages/incremental-merkle-tree/src/insert.ts
  packages/incremental-merkle-tree/tests/index.test.ts
  packages/protocols/package.json
  packages/protocols/src/utils.ts
  packages/protocols/tests/rln.test.ts
Labels: bug, enhancement

#21 refactor: remove arity parameter from mt functions
  packages/protocols/README.md
  packages/protocols/src/utils.ts
  packages/protocols/tests/rln.test.ts
  packages/protocols/tests/semaphore.test.ts
Labels: refactoring
