Repository privacy-scaling-explorations/zk-kit, pull requests merged in 2023-04, with the labels that each got.

#49 Hashtower init
  packages/hashtower.sol/.env.example
  packages/hashtower.sol/.solcover.js
  packages/hashtower.sol/.solhint.json
  packages/hashtower.sol/.solhintignore
  packages/hashtower.sol/README.md
  packages/hashtower.sol/contracts/HashTower.sol
  packages/hashtower.sol/contracts/README.md
  packages/hashtower.sol/contracts/package.json
  packages/hashtower.sol/contracts/test/HashTowerTest.sol
  packages/hashtower.sol/hardhat.config.ts
  packages/hashtower.sol/package.json
  packages/hashtower.sol/tasks/deploy-ht-test.ts
  packages/hashtower.sol/test/HashTowerTest.ts
  packages/hashtower.sol/test/utils.ts
  packages/hashtower.sol/tsconfig.json
  yarn.lock
Labels: feature :rocket:

#52 Hashtower: emit leaf only and use packed level lengths (and rename)
  packages/hashtower.sol/contracts/HashTower.sol
  packages/hashtower.sol/contracts/HashTowerHashChain.sol
  packages/hashtower.sol/contracts/test/HashTowerHashChainTest.sol
  packages/hashtower.sol/tasks/deploy-ht-test.ts
  packages/hashtower.sol/test/HashTowerHashChainTest.ts
Labels: refactoring :recycle:

#55 chore: bump poseidon-solidity
  packages/hashtower.sol/contracts/package.json
  packages/hashtower.sol/package.json
  packages/incremental-merkle-tree.sol/contracts/package.json
  packages/incremental-merkle-tree.sol/package.json
  yarn.lock
Labels: dependencies :package:
